### ISSUE TITLE
Scrollbars not in-sync

### ISSUE THREAD

**Issue by ggrossetie** [rouge-ruby/dingus#8]
A picture is worth a thousand words and a gif is worth a thousand pictures!

![scrollbar](https://user-images.githubusercontent.com/333276/73727028-f903ce80-4730-11ea-93e5-9f4e83367b93.gif)

When I'm using F5, it's working as expected the scrollbar is at the top on both `<textarea>` but if I manually select a language then the scrollbar is at the bottom.

**Comment by pyrmont** [comment]
I haven't looked at the JavaScript yet but this looks like a bug in the way I'm trying to have the highlighted code scroll together with the source. Will have a look and see what's wrong in the next couple of days.
